/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A summary of an individual Automation workflow's settings and content.
type AutomationWorkflow1 struct {
	Recipients *List1 `json:"recipients"`
	Settings *AutomationCampaignSettings1 `json:"settings,omitempty"`
	TriggerSettings *AutomationTrigger1 `json:"trigger_settings"`
}
