/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// Check if this ad is connected to a facebook page
type InlineResponse20011Feedback struct {
	// Feedback regarding the content of this Ad.
	Content string `json:"content,omitempty"`
	// Feedback regarding the audience of this Ad.
	Audience string `json:"audience,omitempty"`
	// Feedback regarding the budget of this Ad.
	Budget string `json:"budget,omitempty"`
	// Feedback regarding the compliance of this Ad.
	Compliance string `json:"compliance,omitempty"`
}
