/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing
import (
	"time"
)

// A subscriber's status for a specific campaign.
type SentTo1 struct {
	// The MD5 hash of the lowercase version of the list member's email address.
	EmailId string `json:"email_id,omitempty"`
	// Email address for a subscriber.
	EmailAddress string `json:"email_address,omitempty"`
	// A dictionary of merge fields where the keys are the merge tags. See the [Merge Fields documentation](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for more about the structure.
	MergeFields map[string]interface{} `json:"merge_fields,omitempty"`
	// [VIP status](https://mailchimp.com/help/designate-and-send-to-vip-contacts/) for subscriber.
	Vip bool `json:"vip,omitempty"`
	// The status of the member ('sent', 'hard' for hard bounce, or 'soft' for soft bounce).
	Status string `json:"status,omitempty"`
	// The number of times a campaign was opened by this member.
	OpenCount int32 `json:"open_count,omitempty"`
	// The date and time of the last open for this member in ISO 8601 format.
	LastOpen time.Time `json:"last_open,omitempty"`
	// For A/B Split Campaigns, the group the member was apart of ('a', 'b', or 'winner').
	AbsplitGroup string `json:"absplit_group,omitempty"`
	// For campaigns sent with timewarp, the time zone group the member is apart of.
	GmtOffset int32 `json:"gmt_offset,omitempty"`
	// The campaign id.
	CampaignId string `json:"campaign_id,omitempty"`
	// The unique list id.
	ListId string `json:"list_id,omitempty"`
	// The status of the list used, namely if it's deleted or disabled.
	ListIsActive bool `json:"list_is_active,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
