/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// Subscriber location information.
type Location struct {
	// The location latitude.
	Latitude float64 `json:"latitude,omitempty"`
	// The location longitude.
	Longitude float64 `json:"longitude,omitempty"`
}
