/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing
import (
	"time"
)

// A summary of an individual Automation workflow's settings and content.
type AutomationWorkflow1 struct {
	// A string that identifies the Automation.
	Id string `json:"id,omitempty"`
	// The date and time the Automation was created in ISO 8601 format.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The date and time the Automation was started in ISO 8601 format.
	StartTime time.Time `json:"start_time,omitempty"`
	// The current status of the Automation.
	Status string `json:"status,omitempty"`
	// The total number of emails sent for the Automation.
	EmailsSent int32 `json:"emails_sent,omitempty"`
	Recipients *List9 `json:"recipients,omitempty"`
	Settings *AutomationCampaignSettings1 `json:"settings,omitempty"`
	Tracking *AutomationTrackingOptions `json:"tracking,omitempty"`
	TriggerSettings *AutomationTrigger1 `json:"trigger_settings,omitempty"`
	ReportSummary *CampaignReportSummary2 `json:"report_summary,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
