/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LandingPageReportTimeseries struct {
	DailyStats *DailyClicksAndVisitsData `json:"daily_stats,omitempty"`
	WeeklyStats *WeeklyClicksAndVisitsData `json:"weekly_stats,omitempty"`
}
