/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type InlineResponse20011Content struct {
	Title string `json:"title,omitempty"`
	LinkUrl string `json:"link_url,omitempty"`
	Message string `json:"message,omitempty"`
	Description string `json:"description,omitempty"`
	ImageUrl string `json:"image_url,omitempty"`
	CallToAction string `json:"call_to_action,omitempty"`
	Attachments []InlineResponse20011ContentAttachments `json:"attachments,omitempty"`
}
