/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The outreach associated with this order. For example, an email campaign or Facebook ad.
type Outreach1 struct {
	// A unique identifier for the outreach. Can be an email campaign ID.
	Id string `json:"id,omitempty"`
}
