/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A summary of an individual campaign's settings and content.
type Campaign struct {
	// There are four types of [campaigns](https://mailchimp.com/help/getting-started-with-campaigns/) you can create in Mailchimp. A/B Split campaigns have been deprecated and variate campaigns should be used instead.
	Type_ string `json:"type"`
	Recipients *List1 `json:"recipients,omitempty"`
	Settings *CampaignSettings1 `json:"settings,omitempty"`
	VariateSettings *AbTestOptions `json:"variate_settings,omitempty"`
	Tracking *CampaignTrackingOptions `json:"tracking,omitempty"`
	RssOpts *RssOptions `json:"rss_opts,omitempty"`
	SocialCard *CampaignSocialCard `json:"social_card,omitempty"`
	// How the campaign's content is put together. The old drag and drop editor uses 'template' while the new editor uses 'multichannel'. Defaults to template.
	ContentType string `json:"content_type,omitempty"`
}
