/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A summary of a specific list's growth activity for a specific month and year.
type GrowthHistory2 struct {
	// The list id for the growth activity report.
	ListId string `json:"list_id,omitempty"`
	// The month that the growth history is describing.
	Month string `json:"month,omitempty"`
	// (deprecated)
	Existing int32 `json:"existing,omitempty"`
	// (deprecated)
	Imports int32 `json:"imports,omitempty"`
	// (deprecated)
	Optins int32 `json:"optins,omitempty"`
	// Total subscribed members on the list at the end of the month.
	Subscribed int32 `json:"subscribed,omitempty"`
	// Newly unsubscribed members on the list for a specific month.
	Unsubscribed int32 `json:"unsubscribed,omitempty"`
	// Newly reconfirmed members on the list for a specific month.
	Reconfirm int32 `json:"reconfirm,omitempty"`
	// Newly cleaned (hard-bounced) members on the list for a specific month.
	Cleaned int32 `json:"cleaned,omitempty"`
	// Pending members on the list for a specific month.
	Pending int32 `json:"pending,omitempty"`
	// Newly deleted members on the list for a specific month.
	Deleted int32 `json:"deleted,omitempty"`
	// Subscribers that have been sent transactional emails via Mandrill.
	Transactional int32 `json:"transactional,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
