/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type InlineResponse20013AudienceActivityClicks struct {
	Date string `json:"date,omitempty"`
	Clicks int32 `json:"clicks,omitempty"`
}
