/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type InlineResponse20011Budget struct {
	// Duration of the ad in seconds
	Duration int32 `json:"duration,omitempty"`
	// Total budget of the ad
	TotalAmount float64 `json:"total_amount,omitempty"`
	// Currency code
	CurrencyCode string `json:"currency_code,omitempty"`
}
