/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type InlineResponse20013ReportSummaryAverageOrderAmount struct {
	Amount float64 `json:"amount,omitempty"`
	CurrencyCode string `json:"currency_code,omitempty"`
}
