/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type InlineResponse2009 struct {
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
	Audience *InlineResponse2009Audience `json:"audience,omitempty"`
	Budget *InlineResponse2009Budget `json:"budget,omitempty"`
	CanceledAt time.Time `json:"canceled_at,omitempty"`
	Channel *InlineResponse2009Channel `json:"channel,omitempty"`
	Content *InlineResponse2009Content `json:"content,omitempty"`
	CreateTime time.Time `json:"create_time,omitempty"`
	EmailSourceName string `json:"email_source_name,omitempty"`
	EndTime time.Time `json:"end_time,omitempty"`
	Feedback *InlineResponse2009Feedback `json:"feedback,omitempty"`
	// Check if this ad has audience setup
	HasAudience bool `json:"has_audience,omitempty"`
	// Check if this ad has content
	HasContent bool `json:"has_content,omitempty"`
	HasSegment bool `json:"has_segment,omitempty"`
	// Unique ID of an Outreach
	Id string `json:"id,omitempty"`
	// Check if this ad is connected to a facebook page
	IsConnected bool `json:"is_connected,omitempty"`
	// Title or name of an Outreach
	Name string `json:"name,omitempty"`
	NeedsAttention bool `json:"needs_attention,omitempty"`
	PausedAt time.Time `json:"paused_at,omitempty"`
	PublishedTime time.Time `json:"published_time,omitempty"`
	Recipients *List10 `json:"recipients,omitempty"`
	ReportSummary *InlineResponse2009ReportSummary `json:"report_summary,omitempty"`
	// Outreach report availability
	ShowReport bool `json:"show_report,omitempty"`
	Site *InlineResponse2009Site `json:"site,omitempty"`
	StartTime time.Time `json:"start_time,omitempty"`
	// Campaign, Ad, or Page status
	Status string `json:"status,omitempty"`
	// The URL of the thumbnail for this outreach
	Thumbnail string `json:"thumbnail,omitempty"`
	// Supported Campaign, Ad, Page type
	Type_ string `json:"type,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	WasCanceledByFacebook bool `json:"was_canceled_by_facebook,omitempty"`
	// Web ID
	WebId int32 `json:"web_id,omitempty"`
}
