/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type InlineResponse20013AudienceActivity struct {
	Clicks []InlineResponse20013AudienceActivityClicks `json:"clicks,omitempty"`
	Impressions []InlineResponse20013AudienceActivityImpressions `json:"impressions,omitempty"`
	Revenue []InlineResponse20013AudienceActivityRevenue `json:"revenue,omitempty"`
}
