/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// The possible sources of any events that can trigger the webhook and whether they are enabled.
type Sources1 struct {
	// Whether the webhook is triggered by subscriber-initiated actions.
	User bool `json:"user,omitempty"`
	// Whether the webhook is triggered by admin-initiated actions in the web interface.
	Admin bool `json:"admin,omitempty"`
	// Whether the webhook is triggered by actions initiated via the API.
	Api bool `json:"api,omitempty"`
}
