/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing
import (
	"time"
)

type AllOfinlineResponse20012FacebookAdsItems struct {
	EmailSourceName string `json:"email_source_name,omitempty"`
	PausedAt time.Time `json:"paused_at,omitempty"`
	EndTime time.Time `json:"end_time,omitempty"`
	NeedsAttention bool `json:"needs_attention,omitempty"`
	WasCanceledByFacebook bool `json:"was_canceled_by_facebook,omitempty"`
	// Channel settings
	Channel *interface{} `json:"channel,omitempty"`
	// Audience settings
	Audience *interface{} `json:"audience,omitempty"`
	Budget *interface{} `json:"budget,omitempty"`
	// Report summary of facebook ad
	ReportSummary *interface{} `json:"report_summary,omitempty"`
	AudienceActivity *interface{} `json:"audience_activity,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []interface{} `json:"_links,omitempty"`
}
