/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type InlineResponse20011ReportSummaryEcommerce struct {
	TotalRevenue float64 `json:"total_revenue,omitempty"`
	CurrencyCode string `json:"currency_code,omitempty"`
	AverageOrderRevenue float64 `json:"average_order_revenue,omitempty"`
}
