/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A list of a member's subscriber activity in a specific campaign, including opens, clicks, and bounces.
type EmailActivity1 struct {
	// The unique id for the campaign.
	CampaignId string `json:"campaign_id,omitempty"`
	// The unique id for the list.
	ListId string `json:"list_id,omitempty"`
	// The status of the list used, namely if it's deleted or disabled.
	ListIsActive bool `json:"list_is_active,omitempty"`
	// The MD5 hash of the lowercase version of the list member's email address.
	EmailId string `json:"email_id,omitempty"`
	// Email address for a subscriber.
	EmailAddress string `json:"email_address,omitempty"`
	// An array of objects, each showing an interaction with the email.
	Activity []MemberActivity `json:"activity,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
