/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A collection of a cart's line items.
type CartLines struct {
	// The store id.
	StoreId string `json:"store_id,omitempty"`
	// The cart id.
	CartId string `json:"cart_id,omitempty"`
	// An array of objects, each representing a cart's line item.
	Lines []EcommerceCartLineItem5 `json:"lines,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
