/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing
import (
	"time"
)

// Individuals who are currently or have been previously subscribed to this list, including members who have bounced or unsubscribed.
type ListMembers4 struct {
	// The MD5 hash of the lowercase version of the list member's email address.
	Id string `json:"id,omitempty"`
	// Email address for a subscriber.
	EmailAddress string `json:"email_address,omitempty"`
	// An identifier for the address across all of Mailchimp.
	UniqueEmailId string `json:"unique_email_id,omitempty"`
	// As Mailchimp evolves beyond email, you may eventually have contacts without email addresses. While the `id` is the MD5 hash of their email address, this `contact_id` is agnostic of contact’s inclusion of an email address.
	ContactId string `json:"contact_id,omitempty"`
	// The contact's full name.
	FullName string `json:"full_name,omitempty"`
	// The ID used in the Mailchimp web application. View this member in your Mailchimp account at `https://{dc}.admin.mailchimp.com/lists/members/view?id={web_id}`.
	WebId int32 `json:"web_id,omitempty"`
	// Type of email this member asked to get ('html' or 'text').
	EmailType string `json:"email_type,omitempty"`
	// Subscriber's current status.
	Status string `json:"status,omitempty"`
	// A subscriber's reason for unsubscribing.
	UnsubscribeReason string `json:"unsubscribe_reason,omitempty"`
	// Indicates whether a contact consents to 1:1 messaging.
	ConsentsToOneToOneMessaging bool `json:"consents_to_one_to_one_messaging,omitempty"`
	// A dictionary of merge fields where the keys are the merge tags. See the [Merge Fields documentation](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for more about the structure.
	MergeFields map[string]interface{} `json:"merge_fields,omitempty"`
	// The key of this object's properties is the ID of the interest in question.
	Interests map[string]bool `json:"interests,omitempty"`
	Stats *SubscriberStats1 `json:"stats,omitempty"`
	// IP address the subscriber signed up from.
	IpSignup string `json:"ip_signup,omitempty"`
	// The date and time the subscriber signed up for the list in ISO 8601 format.
	TimestampSignup time.Time `json:"timestamp_signup,omitempty"`
	// The IP address the subscriber used to confirm their opt-in status.
	IpOpt string `json:"ip_opt,omitempty"`
	// The date and time the subscribe confirmed their opt-in status in ISO 8601 format.
	TimestampOpt time.Time `json:"timestamp_opt,omitempty"`
	// Star rating for this member, between 1 and 5.
	MemberRating int32 `json:"member_rating,omitempty"`
	// The date and time the member's info was last changed in ISO 8601 format.
	LastChanged time.Time `json:"last_changed,omitempty"`
	// If set/detected, the [subscriber's language](https://mailchimp.com/help/view-and-edit-contact-languages/).
	Language string `json:"language,omitempty"`
	// [VIP status](https://mailchimp.com/help/designate-and-send-to-vip-contacts/) for subscriber.
	Vip bool `json:"vip,omitempty"`
	// The list member's email client.
	EmailClient string `json:"email_client,omitempty"`
	Location *Location3 `json:"location,omitempty"`
	// The marketing permissions for the subscriber.
	MarketingPermissions []MarketingPermission1 `json:"marketing_permissions,omitempty"`
	LastNote *Notes `json:"last_note,omitempty"`
	// The source from which the subscriber was added to this list.
	Source string `json:"source,omitempty"`
	// The number of tags applied to this member.
	TagsCount int32 `json:"tags_count,omitempty"`
	// Returns up to 50 tags applied to this member. To retrieve all tags see [Member Tags](https://mailchimp.com/developer/marketing/api/list-member-tags/).
	Tags []ListMembers1Tags `json:"tags,omitempty"`
	// The list id.
	ListId string `json:"list_id,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
