/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing
import (
	"time"
)

// A report of links clicked in a specific campaign.
type ClickDetailReport2 struct {
	// The unique id for the link.
	Id string `json:"id,omitempty"`
	// The URL for the link in the campaign.
	Url string `json:"url,omitempty"`
	// The number of total clicks for a link.
	TotalClicks int32 `json:"total_clicks,omitempty"`
	// The percentage of total clicks a link generated for a campaign.
	ClickPercentage float64 `json:"click_percentage,omitempty"`
	// Number of unique clicks for a link.
	UniqueClicks int32 `json:"unique_clicks,omitempty"`
	// The percentage of unique clicks a link generated for a campaign.
	UniqueClickPercentage float64 `json:"unique_click_percentage,omitempty"`
	// The date and time for the last recorded click for a link in ISO 8601 format.
	LastClick time.Time `json:"last_click,omitempty"`
	AbSplit *AbSplit `json:"ab_split,omitempty"`
	// The campaign id.
	CampaignId string `json:"campaign_id,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
