/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

type BatchAddremoveListMembersTofromStaticSegmentErrors struct {
	// Email addresses added to the static segment or removed
	EmailAddresses []string `json:"email_addresses,omitempty"`
	// The error message indicating why the email addresses could not be added or updated.
	Error_ string `json:"error,omitempty"`
}
