/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The Connected Site associated with the store.
type ConnectedSite2 struct {
	// The unique identifier for the connected site.
	SiteForeignId string `json:"site_foreign_id,omitempty"`
	SiteScript *Script1 `json:"site_script,omitempty"`
}
