/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A webhook configured for batch status updates.
type BatchWebhook3 struct {
	// A string that uniquely identifies this Batch Webhook.
	Id string `json:"id,omitempty"`
	// A valid URL for the Webhook.
	Url string `json:"url,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
