/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A summary of an individual campaign's settings and content.
type Campaign2 struct {
	Recipients *List2 `json:"recipients,omitempty"`
	Settings *CampaignSettings2 `json:"settings"`
	VariateSettings *AbTestOptions `json:"variate_settings,omitempty"`
	Tracking *CampaignTrackingOptions `json:"tracking,omitempty"`
	RssOpts *RssOptions1 `json:"rss_opts,omitempty"`
	SocialCard *CampaignSocialCard `json:"social_card,omitempty"`
}
