/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A summary of an individual Automation workflow's settings and content.
type AutomationWorkflow struct {
	Recipients *List `json:"recipients"`
	Settings *AutomationCampaignSettings `json:"settings,omitempty"`
	TriggerSettings *AutomationTrigger `json:"trigger_settings"`
}
