/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// Webhook configured for the given list.
type ListWebhooks2 struct {
	// An string that uniquely identifies this webhook.
	Id string `json:"id,omitempty"`
	// A valid URL for the Webhook.
	Url string `json:"url,omitempty"`
	Events *Events2 `json:"events,omitempty"`
	Sources *Sources1 `json:"sources,omitempty"`
	// The unique id for the list.
	ListId string `json:"list_id,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
