/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.76
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package mcapimarketing

// A summary of the subscribers who were removed from an Automation workflow.
type RemovedSubscribers struct {
	// A string that uniquely identifies an Automation workflow.
	WorkflowId string `json:"workflow_id,omitempty"`
	// An array of objects, each representing a subscriber who was removed from an Automation workflow.
	Subscribers []SubscriberRemovedFromAutomationWorkflow1 `json:"subscribers,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
